## 应用名称
#spring.application.name=demo
## 应用服务 WEB 访问端口
#server.port=9095
##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.testcreated.demo.mybatis.entity
## 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 数据源名称
#spring.datasource.name=testcreated
## 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/testcreated?serverTimezone=UTC
## 数据库用户名&密码：
#spring.datasource.username=jtons
#spring.datasource.password=123456
#spring.datasource.dynamic.primary=master


# 本地
#server:
#    port: 9002
#
#    tomcat:
#        uri-encoding: UTF-8
#
#file-save-path: D:\personnel\images\
#
#
#
#spring:
#    datasource:
#        dynamic:
#            primary: business
#            strict: false
#            datasource:
#                business:
#                    username: root
#                    password: 123456
#                    url: jdbc:mysql://localhost:3306/personnel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#                    driver-class-name: com.mysql.jdbc.Driver
#    mvc:
#        view:
#            prefix: /
#            suffix: .jsp
#    servlet:
#        multipart:
#            max-file-size: -1
#            max-request-size: -1

# 生产
server:
    port: 9067

    tomcat:
        uri-encoding: UTF-8

file-save-path: /www/wwwfiles/personnel/images/



spring:
    datasource:
        dynamic:
            primary: business
            strict: false
            datasource:
                business:
                    username: crew_server
                    password: crew_server
                    url: jdbc:mysql://8.130.68.133:5050/personnel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
                    driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
            prefix: /
            suffix: .jsp
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1
#












#mybatis:
#    mapper-locations: classpath:mappers/*xml
#    type-aliases-package: com.testcreated.demo.mybatis.entity



#showSql
logging:
    level:
        com:
            jtons:
                personnel:
                    mapper : debug

